#!/bin/bash

if [ -z "$PYFILE" ]; then
	echo "Error: PYFILE environment variable is not set."
	exit 1
fi

python3 -m py_compile "$PYFILE"

if [ $? -eq 0 ]; then
	echo "Compiling $PYFILE ..."
else
	echo "Error: Compilation failed."
	exit 1
fi
